export type PackageStatus = "active" | "maintenance" | "deprecated";
export type PackageStability = "stable" | "beta" | "experimental";
export type PackageKind = "component" | "foundation" | "utility";

export interface PackageCatalogEntry {
  /**
   * The package name published to npm and the folder name under modules/.
   */
  name: string;
  title: string;
  summary: string;
  category: string;
  kind: PackageKind;
  status: PackageStatus;
  stability: PackageStability;
  owner: string;
  buildConfigPath: string;
  docsPath?: string;
  notes?: string;
}

const defaultOwner = "JB Design System maintainers";
const moduleBuildConfigPath = (packageName: string) => `modules/${packageName}/build-config.ts`;

export const packageCatalog: PackageCatalogEntry[] = [
  {
    name: "jb-core",
    title: "Core",
    summary: "Shared browser, theme, i18n, event, and React helper utilities used across packages.",
    category: "Foundation",
    kind: "foundation",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-core"),
  },
  {
    name: "jb-validation",
    title: "Validation",
    summary: "Validation primitives shared by form controls.",
    category: "Foundation",
    kind: "foundation",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-validation"),
  },
  {
    name: "jb-form",
    title: "Form",
    summary: "Form container and value collection tools for JB form controls.",
    category: "Forms",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-form"),
  },
  {
    name: "jb-input",
    title: "Input",
    summary: "Text input with labels, validation, messages, native form behavior, and styling hooks.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-input"),
  },
  {
    name: "jb-number-input",
    title: "Number Input",
    summary: "Number entry control with validation and localized formatting support.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-number-input"),
  },
  {
    name: "jb-mobile-input",
    title: "Mobile Input",
    summary: "Mobile phone input built for validated product forms.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-mobile-input"),
  },
  {
    name: "jb-password-input",
    title: "Password Input",
    summary: "Password field with the expected visibility, validation, and form-control behavior.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-password-input"),
  },
  {
    name: "jb-payment-input",
    title: "Payment Input",
    summary: "Payment and bank-card input patterns for Iranian financial product flows.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-payment-input"),
  },
  {
    name: "jb-national-input",
    title: "National ID Input",
    summary: "National ID entry control with validation-focused form behavior.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-national-input"),
  },
  {
    name: "jb-date-input",
    title: "Date Input",
    summary: "Date entry control designed for localized calendar workflows.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-date-input"),
  },
  {
    name: "jb-time-input",
    title: "Time Input",
    summary: "Time entry control for forms that need structured time values.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-time-input"),
  },
  {
    name: "jb-pin-input",
    title: "PIN Input",
    summary: "Segmented one-time-code and PIN entry control.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-pin-input"),
  },
  {
    name: "jb-textarea",
    title: "Textarea",
    summary: "Multi-line text field with validation, messages, and form integration.",
    category: "Inputs",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-textarea"),
  },
  {
    name: "jb-select",
    title: "Select",
    summary: "Selection control with option rendering, custom selected values, and overlay behavior.",
    category: "Choices",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-select"),
  },
  {
    name: "jb-checkbox",
    title: "Checkbox",
    summary: "Boolean choice control with accessible form behavior.",
    category: "Choices",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-checkbox"),
  },
  {
    name: "jb-switch",
    title: "Switch",
    summary: "Binary on/off control for settings and preference flows.",
    category: "Choices",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-switch"),
  },
  {
    name: "jb-button",
    title: "Button",
    summary: "Action button component with consistent styling and states.",
    category: "Actions",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-button"),
  },
  {
    name: "jb-calendar",
    title: "Calendar",
    summary: "Calendar UI for localized date selection, including Persian-calendar workflows.",
    category: "Pickers",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-calendar"),
  },
  {
    name: "jb-time-picker",
    title: "Time Picker",
    summary: "Picker UI for selecting time values.",
    category: "Pickers",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-time-picker"),
  },
  {
    name: "jb-file-input",
    title: "File Input",
    summary: "File picker control with form integration and validation-ready states.",
    category: "Pickers",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-file-input"),
  },
  {
    name: "jb-image-input",
    title: "Image Input",
    summary: "Image upload input with user-facing preview and file-selection behavior.",
    category: "Pickers",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-image-input"),
  },
  {
    name: "jb-modal",
    title: "Modal",
    summary: "Dialog surface for focused user tasks and confirmation flows.",
    category: "Overlays",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-modal"),
  },
  {
    name: "jb-popover",
    title: "Popover",
    summary: "Anchored floating surface for menus, panels, hints, and lightweight overlays.",
    category: "Overlays",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-popover"),
  },
  {
    name: "jb-tooltip",
    title: "Tooltip",
    summary: "Small contextual help surface for explaining controls and dense UI.",
    category: "Overlays",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-tooltip"),
  },
  {
    name: "jb-notification",
    title: "Notification",
    summary: "User feedback notification component and related notification helpers.",
    category: "Feedback",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-notification"),
    notes: "Includes notification manager and wrapper companion packages in the same repository.",
  },
  {
    name: "jb-loading",
    title: "Loading",
    summary: "Loading indicator for asynchronous states.",
    category: "Feedback",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-loading"),
  },
  {
    name: "jb-grid",
    title: "Grid",
    summary: "Data grid foundation for tabular product interfaces.",
    category: "Data Display",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-grid"),
  },
  {
    name: "jb-searchbar",
    title: "Searchbar",
    summary: "Search input and filter entry point for list and data-heavy views.",
    category: "Data Display",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-searchbar"),
  },
  {
    name: "jb-infinite-scroll",
    title: "Infinite Scroll",
    summary: "Infinite loading behavior for feeds, lists, and lazy data surfaces.",
    category: "Data Display",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-infinite-scroll"),
  },
  {
    name: "jb-qrcode",
    title: "QR Code",
    summary: "QR code rendering component for share, payment, and identity flows.",
    category: "Data Display",
    kind: "component",
    status: "active",
    stability: "stable",
    owner: defaultOwner,
    buildConfigPath: moduleBuildConfigPath("jb-qrcode"),
  },
];
