import { dirname, fromFileUrl, isAbsolute, join, relative, resolve } from "@std/path";

const decoder = new TextDecoder();
const scriptDir = dirname(fromFileUrl(import.meta.url));
const repoRoot = resolve(scriptDir, "../..");
const validatorPath = resolve(scriptDir, "validate-commit-message.ts");
const submoduleFile = join(repoRoot, ".gitmodules");

function git(args: string[], cwd = repoRoot): string {
  const output = new Deno.Command("git", {
    args,
    cwd,
    stdout: "piped",
    stderr: "piped",
  }).outputSync();

  if (!output.success) {
    const message = decoder.decode(output.stderr).trim();
    throw new Error(message || `git ${args.join(" ")} failed`);
  }

  return decoder.decode(output.stdout).trim();
}

function pathExists(path: string): boolean {
  try {
    Deno.statSync(path);
    return true;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      return false;
    }
    throw error;
  }
}

function isDirectory(path: string): boolean {
  try {
    return Deno.statSync(path).isDirectory;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      return false;
    }
    throw error;
  }
}

function toPosixPath(path: string): string {
  return path.replace(/\\/g, "/");
}

function quoteForShell(path: string): string {
  return `'${toPosixPath(path).replace(/'/g, "'\\''")}'`;
}

function getGitDir(worktreePath: string): string {
  const output = git(["rev-parse", "--git-dir"], worktreePath);
  return isAbsolute(output) ? output : resolve(worktreePath, output);
}

function installCommitMsgHook(worktreePath: string): void {
  const gitDir = getGitDir(worktreePath);
  const hooksDir = join(gitDir, "hooks");
  const hookPath = join(hooksDir, "commit-msg");
  const relativeWorktree = relative(repoRoot, worktreePath) || ".";

  Deno.mkdirSync(hooksDir, { recursive: true });
  Deno.writeTextFileSync(
    hookPath,
    `#!/bin/sh
# Generated by tasks/git-hooks/install-git-hooks.ts
deno run --allow-read ${quoteForShell(validatorPath)} "$1"
`,
    { mode: 0o755 },
  );

  console.log(`installed commit-msg hook: ${relativeWorktree}`);
}

function getSubmodulePaths(): string[] {
  if (!pathExists(submoduleFile)) {
    return [];
  }

  const content = Deno.readTextFileSync(submoduleFile);
  return [...content.matchAll(/^\s*path\s*=\s*(.+)\s*$/gm)].map((match) =>
    match[1].trim()
  );
}

installCommitMsgHook(repoRoot);

for (const submodulePath of getSubmodulePaths()) {
  const absoluteSubmodulePath = resolve(repoRoot, submodulePath);

  if (!isDirectory(absoluteSubmodulePath)) {
    console.log(`skipped missing submodule: ${submodulePath}`);
    continue;
  }

  try {
    installCommitMsgHook(absoluteSubmodulePath);
  } catch {
    console.log(`skipped uninitialized submodule: ${submodulePath}`);
  }
}
